workflow 7.x | working with workflow context | LRDOCS-8594
rbohl/liferay-learn pull request #97
Opened 2021-08-05 16:35 UTC by rbohl

Hi @rafaprax, this is the workflow context full draft---well, I am still missing one example---maybe you can help me with it, and review this content.
https://issues.liferay.com/browse/LRDOCS-8594

2021-08-31 14:41 UTC, rbohl commented
Hi @rafaprax I just noticed this one still needs review. Just wanted to remind you.

2021-09-14 13:46 UTC, rafaprax commented
Hey @rbohl,  I'm on it.

2021-09-14 14:17 UTC, rafaprax requested changes
Hey @rbohl, Do you have some scenario/situation that we could use as an example here?  Thx

2021-09-14 14:17 UTC, rafaprax commented on docs/dxp/latest/en/process-automation/workflow/developer-guide/working-with-workflow-context.md
> +
Hey @rbohl, maybe we would set another attribute instead of the "asetTitle" just to avoid this warning. What do you think?

2021-09-21 18:31 UTC, rbohl commented on docs/dxp/latest/en/process-automation/workflow/developer-guide/working-with-workflow-context.md
> +
Is there  a better use case? A lot of assets seem to override the `getTitle` method:
```bash
1. modules/dxp/apps/portal-workflow/portal-workflow-kaleo-forms-web/src/main/java/com/liferay/portal/workflow/kaleo/forms/web/internal/asset/KaleoProcessAssetRenderer.java
2. modules/apps/commerce/commerce-order-web/src/main/java/com/liferay/commerce/order/web/internal/asset/CommerceOrderAssetRenderer.java
3. modules/apps/commerce/commerce-product-definitions-web/src/main/java/com/liferay/commerce/product/definitions/web/internal/asset/CPDefinitionAssetRenderer.java
4. modules/apps/message-boards/message-boards-web/src/main/java/com/liferay/message/boards/web/internal/asset/model/MBThreadAssetRenderer.java
5. modules/apps/message-boards/message-boards-web/src/main/java/com/liferay/message/boards/web/internal/asset/model/MBCategoryAssetRenderer.java
6. modules/apps/message-boards/message-boards-web/src/main/java/com/liferay/message/boards/web/internal/asset/model/MBMessageAssetRenderer.java
7. modules/apps/layout/layout-admin-web/src/main/java/com/liferay/layout/admin/web/internal/asset/model/LayoutRevisionAssetRenderer.java
8. modules/apps/layout/layout-admin-web/src/main/java/com/liferay/layout/admin/web/internal/asset/model/LayoutAssetRenderer.java
9. modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-web/src/main/java/com/liferay/dynamic/data/mapping/form/web/internal/asset/model/DDMFormAssetRenderer.java
10. modules/apps/questions/questions-web/src/main/java/com/liferay/questions/web/internal/asset/model/MBCategoryAssetRenderer.java
11. modules/apps/questions/questions-web/src/main/java/com/liferay/questions/web/internal/asset/model/MBMessageAssetRenderer.java
12. modules/apps/bookmarks/bookmarks-web/src/main/java/com/liferay/bookmarks/web/internal/asset/model/BookmarksRootFolderAssetRenderer.java
13. modules/apps/bookmarks/bookmarks-web/src/main/java/com/liferay/bookmarks/web/internal/asset/model/BookmarksEntryAssetRenderer.java
14. modules/apps/bookmarks/bookmarks-web/src/main/java/com/liferay/bookmarks/web/internal/asset/model/BookmarksFolderAssetRenderer.java
15. modules/apps/microblogs/microblogs-web/src/main/java/com/liferay/microblogs/web/internal/asset/model/MicroblogsEntryAssetRenderer.java
16. modules/apps/translation/translation-web/src/main/java/com/liferay/translation/web/internal/asset/model/TranslationEntryAssetRenderer.java
17. modules/apps/knowledge-base/knowledge-base-web/src/main/java/com/liferay/knowledge/base/web/internal/asset/model/KBArticleAssetRenderer.java
18. modules/apps/document-library/document-library-web/src/main/java/com/liferay/document/library/web/internal/asset/model/DLFolderAssetRenderer.java
19. modules/apps/document-library/document-library-web/src/main/java/com/liferay/document/library/web/internal/asset/model/DLFileEntryAssetRenderer.java
20. modules/apps/calendar/calendar-web/src/main/java/com/liferay/calendar/web/internal/asset/model/CalendarBookingAssetRenderer.java
21. modules/apps/dynamic-data-lists/dynamic-data-lists-web/src/main/java/com/liferay/dynamic/data/lists/web/internal/asset/model/DDLRecordAssetRenderer.java
22. modules/apps/site/site-admin-web/src/main/java/com/liferay/site/admin/web/internal/asset/model/SiteAssetRenderer.java
23. modules/apps/archived/directory-web/src/main/java/com/liferay/directory/web/internal/asset/model/OrganizationAssetRenderer.java
24. modules/apps/blogs/blogs-web/src/main/java/com/liferay/blogs/web/internal/asset/model/BlogsEntryAssetRenderer.java
25. modules/apps/contacts/contacts-web/src/main/java/com/liferay/contacts/web/internal/asset/model/UserAssetRenderer.java
26. modules/apps/comment/comment-web/src/main/java/com/liferay/comment/web/internal/asset/model/CommentAssetRenderer.java
27. modules/apps/wiki/wiki-web/src/main/java/com/liferay/wiki/web/internal/asset/model/WikiPageAssetRenderer.java
28. modules/apps/journal/journal-web/src/main/java/com/liferay/journal/web/internal/asset/model/JournalArticleAssetRenderer.java
29. modules/apps/journal/journal-web/src/main/java/com/liferay/journal/web/internal/asset/model/JournalFolderAssetRenderer.java
```

2021-09-21 18:51 UTC, rbohl commented
> Hey @rbohl, Do you have some scenario/situation that we could use as an example here? I'm not so inspired today  Thx

Well, looking around in the Local Service Impl classes, I don't see anything that strikes me as interesting to add to the workflow context. :thinking:

2021-10-04 12:56 UTC, rafaprax reviewed
> Well, looking around in the Local Service Impl classes, I don't see anything that strikes me as interesting to add to the workflow context. 🤔

So, is it possible to finish this without a real example? Thx

2021-10-04 12:56 UTC, rafaprax commented on docs/dxp/latest/en/process-automation/workflow/developer-guide/working-with-workflow-context.md
> +
@rbohl Oh Sorry. Got it. It's the `assetTitle` from the AssetRenderer implementation. Thx for clarifying.

2021-10-04 15:26 UTC, rbohl commented
> > Well, looking around in the Local Service Impl classes, I don't see anything that strikes me as interesting to add to the workflow context. thinking
> 
> So, is it possible to finish this without a real example? Thx

We could do that, but I'd rather just leave this part out for now, if we can't think of why a user would want to set the data into the workflow context into the service layer. Besides we already cover how to set attributes into the service context, then access them in the workflow. So the use case seems to be pretty similar.

2021-10-05 12:00 UTC, rbohl commented
Forwarded with changes: https://github.com/sez11a/liferay-learn/pull/593

Thanks!

2021-10-05 12:00 UTC, closed without merging